#!/bin/sh
##############################################################################€
#
# Generic ramdisk init process for booting a device. Based Marko Saukko's
# initrd for Galaxy Note GT-i9250. RAF reworked
#
# Copyright (C) 2014 Jolla Ltd.
# Copyright (C) 2012 Marko Saukko
# Copyright (C) 2023 Roberto A. Foglietta
#     Contact: roberto.foglietta@gmail.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#
# IRC: Sage @ #mer & #nemomobile @ Freenode
#
###############################################################################
# release: 0.0.5

export PATH=/usr/bin:/usr/sbin:/bin:/sbin

###############################################################################

ANDROID_USB=/sys/class/android_usb/android0
GADGET_DIR=/config/usb_gadget
USB_FUNCTIONS=rndis
LOCAL_IP=10.42.66.66

write()
{
	echo -n "$2" > "$1"
}

# This sets up the USB with whatever USB_FUNCTIONS are set to via configfs
usb_setup_configfs() {
    G_USB_ISERIAL=$GADGET_DIR/g1/strings/0x409/serialnumber
    mkdir $GADGET_DIR/g1
    write $GADGET_DIR/g1/idVendor                   "0x2931"
    write $GADGET_DIR/g1/idProduct                  "0x0A06"
    mkdir $GADGET_DIR/g1/strings/0x409
    write $GADGET_DIR/g1/strings/0x409/serialnumber "$1"
    write $GADGET_DIR/g1/strings/0x409/manufacturer "robang74"
    write $GADGET_DIR/g1/strings/0x409/product      "usblink"

    if echo $USB_FUNCTIONS | grep -q "rndis"; then
        mkdir $GADGET_DIR/g1/functions/rndis.rndis0
        mkdir $GADGET_DIR/g1/functions/rndis_bam.rndis
    fi

    mkdir $GADGET_DIR/g1/configs/c.1
    mkdir $GADGET_DIR/g1/configs/c.1/strings/0x409
    write $GADGET_DIR/g1/configs/c.1/strings/0x409/configuration "$USB_FUNCTIONS"

    if echo $USB_FUNCTIONS | grep -q "rndis"; then
        ln -s $GADGET_DIR/g1/functions/rndis.rndis0 $GADGET_DIR/g1/configs/c.1
        ln -s $GADGET_DIR/g1/functions/rndis_bam.rndis $GADGET_DIR/g1/configs/c.1
    fi

    echo "$(ls /sys/class/udc)" > $GADGET_DIR/g1/UDC
}

# This sets up the USB with whatever USB_FUNCTIONS are set to via android_usb
usb_setup_android_usb() {
    G_USB_ISERIAL=$ANDROID_USB/iSerial
    write $ANDROID_USB/enable          0
    write $ANDROID_USB/functions       ""
    write $ANDROID_USB/enable          1
    usleep 500000 # 0.5 delay to attempt to remove rndis function
    write $ANDROID_USB/enable          0
    write $ANDROID_USB/idVendor        2931
    write $ANDROID_USB/idProduct       0A06
    write $ANDROID_USB/iManufacturer   "robang74"
    write $ANDROID_USB/iProduct        "usblink"
    write $ANDROID_USB/iSerial         "$1"
    write $ANDROID_USB/functions       $USB_FUNCTIONS
    write $ANDROID_USB/enable          1
}

# This determines which USB setup method is going to be used
usb_setup() {
    if [ -f $ANDROID_USB/enable ]; then
        usb_setup_android_usb $1
    else
        usb_setup_configfs $1
    fi
}

###############################################################################

/sbin/busybox-static --install -s

echo "Doing mounts... "
mount /dev
mkdir /dev/pts /dev/shm
mount -a
cat /proc/mounts >/etc/mtab
mount -t configfs none /config

echo "Running mdev..."
mdev -s -f
#echo /bin/mdev >/proc/sys/kernel/hotplug

echo "Setting USB gadget..." 
usb_setup "rfos45021" 

for i in 0 1 2 3 4 5 6 7 8 9; do
    dmesg | grep -q configfs-gadget && break
    sleep 1
done

if dmesg | grep -q configfs-gadget; then
    . /init.hr
else
    echo >/proc/sys/kernel/hotplug
    umount /config
    . /init.hb
fi
