#!/bin/sh
################################################################################
#
# Generic ramdisk init process for booting a device. Based Marko Saukko's
# initrd for Galaxy Note GT-i9250. Reworked by Roberto A. Foglietta.
#
# Copyright (C) 2014 Jolla Ltd.
# Copyright (C) 2012 Marko Saukko
# Copyright (C) 2023 Roberto A. Foglietta
#     Contact: roberto.foglietta@gmail.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
################################################################################
# release: 0.1.5

export PATH=/usr/bin:/usr/sbin:/bin:/sbin

/sbin/busybox-static --install -s
/sbin/ldconfig

set -o allexport
. /usr/bin/recovery-functions.env
set +o allexport

LOCAL_IP="10.42.66.66"
LOCAL_BR="10.42.66.255"

USB_IP="192.168.2.15"
USB_BR="192.168.2.255"

################################################################################

hostname $(cat /etc/hostname 2>/dev/null || echo recovery)

echo "Doing mount config and all..."
mount /dev
mkdir /dev/pts /dev/shm
mount -a
cat /proc/mounts >/etc/mtab
mount -t configfs none /config

yamui_animation

print-banner.sh $LOCAL_IP >/dev/null &

powerkey-handler.sh start

for i in /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor; do
     echo "conservative" >$i
done

#echo "Running mdev..."
#mdev -s -f
##echo /bin/mdev >/proc/sys/kernel/hotplug

echo "USB config setting..."
. /init.usb

pause 2 # RAF: just to test the animation

for i in $(seq 1 8); do
    dmesg | grep -q configfs-gadget && break
    pause
done

if dmesg | grep -q configfs-gadget; then
    echo "initrd: USB connection found at $i' attempt" > /dev/kmsg
    . /init.hr
else
    echo "initrd: USB connection NOT found, boot mode" > /dev/kmsg
    proc_kill yamui
##  echo >/proc/sys/kernel/hotplug
    umount /config
    . /init.hb
fi
